"use client";
import {FormEvent,useEffect,useState} from "react";
const ny=[
 {name:"La Grande Boucherie",area:"Midtown",address:"145 W 53rd St, New York, NY 10019",phone:"+1 (212) 510-7714",hours:"Mon–Fri 8am–12am · Sat–Sun 9am–12am"},
 {name:"Boucherie West Village",area:"West Village",address:"99 7th Avenue South, New York, NY 10014",phone:"+1 (212) 837-1616",hours:"Mon–Fri 11am–12am · Sat–Sun 10am–12am"},
 {name:"Boucherie Union Square",area:"Union Square",address:"225 Park Avenue South, New York, NY 10003",phone:"+1 (212) 353-0200",hours:"Mon–Fri 11am–12am · Sat–Sun 10am–12am"},
 {name:"Petite Boucherie",area:"West Village",address:"14 Christopher Street, New York, NY 10014",phone:"+1 (646) 756-4145",hours:"Mon–Fri 11am–12am · Sat–Sun 10am–12am"}
];
const book="/reservations";
export default function Home(){const[open,setOpen]=useState(false),[small,setSmall]=useState(false),[city,setCity]=useState("NEW YORK"),[note,setNote]=useState("");useEffect(()=>{const f=()=>setSmall(scrollY>50);addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setNote("Merci — you’re on the list.");e.currentTarget.reset()};return <main>
 <header className={small?"small":""}><a className="logo" href="#top"><b>BOUCHERIE</b><span>RESTAURANT FRANÇAIS</span></a><nav className={open?"open":""}>{[["New York","locations"],["Chicago","locations"],["Miami","locations"],["Washington D.C.","locations"],["Our Story","story"],["Events","events"],["Reviews","reviews"]].map(x=><a key={x[0]} href={`#${x[1]}`} onClick={()=>setOpen(false)}>{x[0]}</a>)}</nav><a className="btn gold desktop-book" href={book}>Book a table</a><button className="hamb" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle menu"><i/><i/></button></header>
 <section className="hero" id="top"><div className="heroShade"/><div className="heroText"><p className="kicker">NEW YORK · CHICAGO · MIAMI · WASHINGTON D.C.</p><h1>Welcome to<br/><em>Boucherie</em></h1><p>A traditional French restaurant celebrating good food and <i>joie de vivre.</i></p><div className="buttons"><a className="btn ivory" href={book}>Book a table</a><a className="link" href="#experience">Explore Boucherie ↘</a></div></div><span className="vertical">LA BELLE ÉPOQUE, REIMAGINED</span></section>
 <section className="intro cream" id="intro"><div className="num">01</div><div><p className="kicker dark">L’ART DE LA TABLE</p><h2>The art of<br/><em>French dining</em></h2><p className="bodycopy">Rooted in French culinary tradition and the carefree spirit of La Belle Époque, Boucherie blends the indulgence of a steakhouse with the soul of a refined Parisian brasserie.</p><a className="link dark" href="#story">Our philosophy →</a></div><div className="portrait"/><blockquote>“Good food is the foundation of genuine happiness.”<small>— Auguste Escoffier</small></blockquote></section>
 <section className="experience darkbg" id="experience"><p className="kicker">THE BOUCHERIE EXPERIENCE</p><h2>Every detail,<br/><em>considered.</em></h2><div className="experiences">{[["01","The food","Time-honored French dishes, exceptional ingredients and the generosity of a true brasserie."],["02","The atmosphere","Ornamental Art Nouveau details, warm light and the effortless romance of Paris."],["03","The experience","Gracious hospitality and evenings designed to become memories."]].map((x,i)=><article key={x[0]}><div className={`exp e${i+1}`}><span>{x[0]}</span></div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section className="dishes cream" id="menu"><div className="heading"><div><p className="kicker dark">À LA CARTE</p><h2>Signatures of<br/><em>the house</em></h2></div><a className="btn outline" href="https://www.boucherieus.com/la-grande-boucherie-menus/">View menu</a></div><div className="dishgrid">{[["Prime Steak Frites","Prime grass-fed New York strip, herb butter, pommes frites","steak"],["Soupe à l’Oignon","Traditional French onion soup, croutons and Gruyère","soup"],["Plateau de Fruits de Mer","A generous selection from the raw bar, designed for sharing","sea"],["Boeuf Bourguignon","Traditional French braised beef, carrots, mushrooms, bacon and pearl onion","beef"]].map((x,i)=><article className={i===0?"featured":""} key={x[0]}><div className={`dish ${x[2]}`} role="img" aria-label={`${x[0]} presentation`}><span>0{i+1}</span></div><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
 <section className="locations wine" id="locations"><p className="kicker">FIND YOUR BOUCHERIE</p><h2>From our table<br/><em>to yours.</em></h2><div className="tabs">{["NEW YORK","CHICAGO","MIAMI","WASHINGTON D.C."].map(x=><button key={x} aria-selected={city===x} onClick={()=>setCity(x)}>{x}</button>)}</div>{city==="NEW YORK"?<div className="loclist">{ny.map((x,i)=><article key={x.name}><span>0{i+1}</span><div><small>{x.area}</small><h3>{x.name}</h3><address>{x.address}<br/>{x.hours}<br/><a href={`tel:${x.phone}`}>{x.phone}</a></address></div><div className="locbuttons"><a href="https://www.boucherieus.com/hours-and-locations/">View location ↗</a><a className="btn ivory" href={book}>Reserve</a></div></article>)}</div>:<div className="city"><small>LA GRANDE BOUCHERIE</small><h3>{city}</h3><p>Discover our grand French brasserie experience.</p><a className="btn ivory" href="https://www.boucherieus.com/hours-and-locations/">View location</a></div>}</section>
 <section className="reserve"><div><p className="kicker">BON APPÉTIT</p><h2>Your table <em>awaits.</em></h2><p>Join us for an unforgettable French dining experience.</p><a className="btn ivory" href={book}>Book a table</a></div></section>
 <section className="story cream" id="story"><div className="storyimg"/><div><p className="kicker dark">NOTRE HISTOIRE</p><h2>The Boucherie<br/><em>story</em></h2><p className="bodycopy">Inspired by the optimism and ornament of La Belle Époque, Boucherie was imagined as a meeting place for the modern city—where centuries-old French culture feels vivid, generous and alive.</p><p className="bodycopy">A celebration of thoughtful sourcing, timeless craft and gathering around a beautiful table.</p><a className="link dark" href="https://www.boucherieus.com/our-story/">Discover our story →</a></div></section>
 <section className="events darkbg" id="events"><div className="heading"><div><p className="kicker">OCCASIONS</p><h2>Gather <em>beautifully.</em></h2></div><a className="btn outline light" href="https://www.boucherieus.com/events/">Explore events</a></div><div className="eventlist">{["Private dining","Celebrations","Corporate events","Special occasions"].map((x,i)=><a href="https://www.boucherieus.com/events/" key={x}><span>0{i+1}</span><h3>{x}</h3><b>↗</b></a>)}</div></section>
 <section className="reviews cream" id="reviews"><p className="stars">✦ ✦ ✦</p><blockquote>Every table tells a story. We invite you to share yours.</blockquote><small>FOOD · SERVICE · AMBIANCE · JOIE DE VIVRE</small><br/><a className="btn outline reviewlink" href="https://www.boucherieus.com/reviews/">Read &amp; leave reviews</a></section>
 <section className="social cream"><div className="heading"><div><p className="kicker dark">@BOUCHERIE_US</p><h2>Follow the<br/><em>experience</em></h2></div><a className="link dark" href="https://www.instagram.com/boucherie_us/">Follow on Instagram ↗</a></div><div className="socialgrid"><div/><div/><div/><div/></div></section>
 <section className="newsletter"><p className="kicker">LE JOURNAL</p><h2>Stay in the know</h2><p>Be the first to hear about special events, new experiences, and what’s happening at Boucherie.</p><form onSubmit={submit}><label className="sr" htmlFor="email">Your email</label><input id="email" type="email" required placeholder="YOUR EMAIL"/><button>Subscribe →</button></form><div aria-live="polite">{note}</div></section>
 <footer><div className="footbrand"><div className="logo"><b>BOUCHERIE</b><span>RESTAURANT FRANÇAIS</span></div><p>A celebration of good food<br/>and <i>joie de vivre.</i></p></div>{[["Visit","New York","Chicago","Miami","Washington D.C."],["Discover","Our Story","Events","Reviews","Careers"],["Connect","Instagram","Facebook","Contact","Press"]].map(x=><div key={x[0]}><h4>{x[0]}</h4>{x.slice(1).map(y=><a href="#locations" key={y}>{y}</a>)}</div>)}<div className="footbottom"><span>© 2026 Boucherie · Redesign concept</span><a href="https://www.boucherieus.com/privacy-policy/">Privacy</a><a href="#top">Back to top ↑</a></div></footer><a className="mobilebook" href={book}>Book a table</a>
 </main>}
